<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>HardwareMonitorInterface</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>

		<!-- Travar em x64, já que você instalou o runtime x64 -->
		<Platforms>x64</Platforms>

		<!-- Remover outras arquiteturas pra não gerar exe x86/arm -->
		<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>

		<!-- WinUI 3 via Windows App SDK -->
		<UseWinUI>true</UseWinUI>
		<WinUISDKReferences>false</WinUISDKReferences>

		<!-- Rodar como app desempacotado (sem MSIX) -->
		<WindowsPackageType>None</WindowsPackageType>

		<!-- Opcional, se não for empacotar em MSIX agora -->
		<EnableMsixTooling>false</EnableMsixTooling>

		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.6901" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.251106002" />
		<PackageReference Include="System.Management" Version="10.0.0" />
		<PackageReference Include="Vortice.DXGI" Version="3.6.2" />
	</ItemGroup>

	<!-- Se deixar o Msix desligado acima, pode remover completamente esses blocos:
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>

  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
  -->

	<PropertyGroup>
		<PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
		<PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
		<PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
		<PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
	</PropertyGroup>
</Project>
